version: "3.8"

services:
  backend:
    volumes:
      - ./bibliflow-backend:/usr/src/app:cached
      - backend_node_modules:/usr/src/app/node_modules

  frontend:
    volumes:
      - ./bibliflow-frontend:/usr/src/app:cached
      - frontend_node_modules:/usr/src/app/node_modules
